In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import sklearn.model_selection as sk
from random import randint
from sklearn.preprocessing import MinMaxScaler
from sklearn.utils import shuffle


import keras
from keras import backend as K
from keras.models import Sequential
from keras.layers import Activation
from keras.layers.core import Dense
from tensorflow.keras.optimizers import Adam
from keras.metrics import categorical_crossentropy

In [2]:
#READ DATA FROM CSV + PADDING/TRUNCATING TO 15

import numpy as np

def read_csv(filename):
    file = open(filename)

    lines = file.readline() # Consumes CSV header
    lines = file.readline()
    lines_list = lines.split(",")
    batch = lines_list[0]
    
    raw_inputs = [[], [], []] # For acceleromter readings xyz wrist and xyz arm

    label_list = []
    label = 0
    
    total_inputs = []

    try:
        while lines:
            lines_list = lines.split(",")
            
#             if int(batch) > 10:
#                 break;

            if batch != lines_list[0]:
                previous_batch = batch
                batch = lines_list[0]
                
#                 padded_inputs = tf.keras.preprocessing.sequence.pad_sequences(
#                     raw_inputs, padding="post", maxlen=100, truncating='post'
#                 )
                total_inputs.append(raw_inputs)
                label_list.append(int(label))
                label = 0


                raw_inputs = [[], [], []] # For acceleromter readings xyz wrist and xyz arm
                raw_inputs[0].append(np.int8(lines_list[5]))
                raw_inputs[1].append(np.int8(lines_list[6]))
                raw_inputs[2].append(np.int8(lines_list[7]))
                print(np.int8(lines_list[7]), lines_list[7])

                
            else:
                label = lines_list[21]
                raw_inputs[0].append(np.int8(lines_list[5]))
                raw_inputs[1].append(np.int8(lines_list[6]))
                raw_inputs[2].append(np.int8(lines_list[7]))

              
                
            lines = file.readline()
    except IndexError:
        print(batch)
        
    return total_inputs, label_list




In [3]:
# a, lable_list = read_csv('new_combine.csv')
# a, lable_list = read_csv('all_combined.csv')

a, lable_list = read_csv('updated.csv')
# combined_samples_one_column = combined_samples.reshape([-1,1])




54 54
47 47
37 37
15 15
36 36
10 10
4 4
-19 -19
16 16
35 35
19 19
29 29
-13 -13
6 6
32 32
2 2
-15 -15
-29 -29
4 4
-17 -17
-16 -16
-39 -39
-25 -25
-51 -51
-23 -23
-34 -34
-3 -3
6 6
-16 -16
-16 -16
-25 -25
-7 -7
9 9
3 3
-4 -4
-1 -1
-14 -14
-22 -22
37 37
-23 -23
20 20
-27 -27
-8 -8
4 4
12 12
-29 -29
20 20
-3 -3
8 8
-9 -9
-15 -15
-32 -32
-47 -47
-20 -20
-31 -31
18 18
75 75
59 59
19 19
59 59
48 48
43 43
42 42
66 66
56 56
1 1
17 17
-67 -67
35 35
40 40
48 48
49 49
55 55
45 45
29 29
15 15
50 50
28 28
5 5
12 12
47 47
43 43
21 21
28 28
56 56
16 16
73 73
19 19
13 13
34 34
4 4
-13 -13
6 6
57 57
-16 -16
59 59
15 15
39 39
10 10
12 12
-9 -9
23 23
40 40
17 17
-7 -7
25 25
3 3
-36 -36
83 83
-17 -17
41 41
13 13
36 36
4 4
41 41
61 61
32 32
21 21
-21 -21
-52 -52
21 21
22 22
-8 -8
42 42
13 13
20 20
32 32
-1 -1
20 20
10 10
13 13
7 7
-26 -26
11 11
-12 -12
0 0
25 25
-2 -2
14 14
-5 -5
45 45
-2 -2
44 44
50 50
45 45
30 30
7 7
37 37
53 53
10 10
-15 -15
47 47
97 97
108 108
45 45
-41 -41
-32 -32
64 64
-22 -22
28 28


In [4]:
combined_samples = []
container = []
for i in range(len(a)):
    for j in range(len(a[0])):
        container.extend(a[i][j])
    combined_samples.append(container)
    container = []


In [5]:
combined_samples = np.array(combined_samples)
lable_list = np.array(lable_list)

combined_samples, lable_list = shuffle(combined_samples, lable_list)

# scaler = MinMaxScaler(feature_range=(0,1))
# combined_samples_one_column = combined_samples.reshape([-1,1])




# result_one_column = scaler.fit_transform(combined_samples_one_column)
# scaled_samples = result_one_column.reshape(combined_samples.shape)


scaled_samples = combined_samples

print(scaled_samples.shape)



(1330, 300)


In [12]:
print(type(combined_samples[0][0]))

<class 'numpy.int8'>


In [6]:
X_train, X_test, y_train, y_test = sk.train_test_split(combined_samples, lable_list, test_size=0.33)


In [9]:
inputs = keras.Input(shape=(300,), dtype=tf.int8)
layer_1 = layers.Dense(64, activation="relu")
layer_1_output = layer_1(inputs) 

layer_2 = layers.Dense(64, activation="relu")
layer_2_output = layer_2(layer_1_output) 

# layer_3 = layers.Dense(64, activation="relu")
# layer_3_output = layer_3(layer_2_output) 

# layer_4 = layers.Dense(64, activation="relu")
# layer_4_output = layer_4(layer_3_output) 

outputs = layers.Dense(5, activation="softmax")(layer_2_output)

In [10]:
model = keras.Model(inputs=inputs, outputs=outputs, name="mnist_model")
model.summary()
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    metrics=["accuracy"],
)


# model.compile(
#     loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
#     optimizer=keras.optimizers.RMSprop(),
#     metrics=["accuracy"],
# )

Model: "mnist_model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 300)]             0         
_________________________________________________________________
dense_4 (Dense)              (None, 64)                19264     
_________________________________________________________________
dense_5 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_6 (Dense)              (None, 5)                 325       
Total params: 23,749
Trainable params: 23,749
Non-trainable params: 0
_________________________________________________________________


In [9]:
import keras.backend as K

def size(model): # Compute number of params in a model (the actual number of floats)
    return sum([np.prod(K.get_value(w).shape) for w in model.trainable_weights])

print(size(model))


23749


In [14]:
model.fit(X_train, y_train, validation_split=0.1, batch_size=10, epochs=5, shuffle=True, verbose=2)

Epoch 1/5
81/81 - 0s - loss: 4.7009e-07 - accuracy: 1.0000 - val_loss: 0.6507 - val_accuracy: 0.9889
Epoch 2/5
81/81 - 0s - loss: 4.3572e-07 - accuracy: 1.0000 - val_loss: 0.6507 - val_accuracy: 0.9889
Epoch 3/5
81/81 - 0s - loss: 4.0790e-07 - accuracy: 1.0000 - val_loss: 0.6507 - val_accuracy: 0.9889
Epoch 4/5
81/81 - 0s - loss: 3.8468e-07 - accuracy: 1.0000 - val_loss: 0.6507 - val_accuracy: 0.9889
Epoch 5/5
81/81 - 0s - loss: 3.5165e-07 - accuracy: 1.0000 - val_loss: 0.6507 - val_accuracy: 0.9889


In [ ]:
X_test = scaled_samples
y_test = lable_list
print(type(X_test[0][0]))

In [8]:


test_scores = model.evaluate(X_test, y_test, verbose=2)
print("Test loss:", test_scores[0])
print("Test accuracy:", test_scores[1])

14/14 - 1s - loss: 0.3136 - accuracy: 0.9886
Test loss: 0.3136259615421295
Test accuracy: 0.9886105060577393


In [7]:
# q = model.predict(test_data[0][None,...])

# model.save('two_layers.h5')
from keras.models import load_model

model = load_model('two_layers.h5')

In [18]:
model.summary()
# model.layers[1].get_weights()

for layer in model.layers:
  print(layer.get_config())

for layer in model.layers:
  print(layer.get_weights())


Model: "mnist_model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 300)]             0         
_________________________________________________________________
dense_4 (Dense)              (None, 64)                19264     
_________________________________________________________________
dense_5 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_6 (Dense)              (None, 5)                 325       
Total params: 23,749
Trainable params: 23,749
Non-trainable params: 0
_________________________________________________________________
{'batch_input_shape': (None, 300), 'dtype': 'int8', 'sparse': False, 'ragged': False, 'name': 'input_2'}
{'name': 'dense_4', 'trainable': True, 'dtype': 'float32', 'units': 64, 'activation': 'relu', 'use_bias': True, 'kernel_initializer': {'class_na

In [94]:
max_int = 0
min_int = 0

test_sam = scaled_samples[1278]
test_label = lable_list[1278]
weights_1 = model.layers[1].get_weights()[0]
biases_1 = model.layers[1].get_weights()[1]


weights_2 = model.layers[2].get_weights()[0]
biases_2  = model.layers[2].get_weights()[1]

weights_3 = model.layers[3].get_weights()[0]
biases_3  = model.layers[3].get_weights()[1]

results = []
results_2 = []
results_3 = []

number_nodes = 64
number_inputs = 300
output_nodes = 5
#     print(len(weights_1))
#     print(len(weights_1[0]))

sum = 0

for i in range(number_nodes):
    for j in range(number_inputs):
        sum += test_sam[j] * weights_1[j][i]
    sum += biases_1[i]
    results.append(max(0, sum))
    sum = 0

sum = 0

for i in range(number_nodes):
    for j in range(len(results)):
        sum += results[j] * weights_2[j][i]
    sum += biases_2[i]
    results_2.append(max(0, sum))
    sum = 0

sum = 0

for i in range(output_nodes):
    for j in range(len(results)):
        sum += results_2[j] * weights_3[j][i]
    sum += biases_3[i]
    results_3.append(sum)
    sum = 0
# if max(results) > max_int:
#     max_int = max(results)
# if max(results_2) > max_int:
#     max_int = max(results_2)
# if max(results_3) > max_int:
#     max_int = max(results_3)

# if min(results) < min_int:
#     min_int = min(results)
# if min(results_2) < min_int:
#     min_int = min(results_2)
# if min(results_3) < min_int:
#     min_int = min(results_3)


        
print(results_3)

[-6.676661611811975, 190.77872379444665, -88.94199811314171, -90.74696566204754, -88.82365704588324]


In [9]:
sample_num = 75

test_sam = scaled_samples[sample_num]    #  75 50 102 147 
test_label = lable_list[sample_num]

q = model.predict(np.array([test_sam]))
print(q)

print(list[test_sam])

print(test_label)


[[4.3104214e-32 0.0000000e+00 1.0000000e+00 1.6908324e-26 3.4133716e-35]]
list[array([ 54,  61,  64,  62,  60,  61,  63,  62,  60,  60,  60,  59,  58,
        57,  56,  51,  49,  46,  42,  36,  33,  29,  25,  21,  14,   8,
         2,  -2,  -5,  -8,  -9, -10, -12, -15, -21, -27, -32, -36, -42,
       -49, -56, -60, -59, -54, -49, -49, -51, -53, -56, -55, -53, -53,
       -53, -47, -41, -39, -37, -36, -34, -33, -33, -32, -31, -30, -29,
       -26, -23, -20, -17, -16, -13, -10,  -8,  -8, -11, -11,  -9,  -6,
        -4,  -4,  -3,  -1,   1,   2,   4,   7,  10,  13,  16,  17,  19,
        20,  22,  24,  27,  29,  31,  32,  32,  32,  -6, -14, -17, -16,
       -11, -13, -18, -22, -24, -25, -24, -23, -24, -26, -26, -23, -21,
       -19, -18, -18, -19, -16, -13,  -7,   1,  10,  18,  25,  30,  35,
        35,  31,  29,  36,  50,  63,  71,  77,  84, 100, 121, 127, 127,
       127, 126, 113, 103,  96, 102, 111, 122, 127, 127, 126, 111, 101,
        91,  82,  78,  77,  79,  81,  85,  89,  90,  88, 

In [85]:
# print("learned weights =", weights)

# # Biases are similar because they are all initialized with zeros (by default).
# print("learned biases =", biases)
from numpy  import exp
from numpy  import sum

def softmax(vector):
    e = exp(vector)
    return e / e.sum()


print("results3 =", results_3)



after_activation = softmax(results_3)
print(after_activation)
print(sum(after_activation))
print(sum(q))


results3 = [-6.676661611811975, 190.77872379444665, -88.94199811314171, -90.74696566204754, -88.82365704588324]
[1.76285136e-086 1.00000000e+000 3.30243289e-122 5.43183482e-123
 3.71731080e-122]
1.0
1.0


In [69]:
for i in range (len(weights_1)):
    print("{", end="")
    for j in range (len(weights_1[0])-1):
        print(f"{weights_1[i][j]},", end="")
    print(f"{weights_1[i][63]}", end="")
    print("},")

# for i in range (len(weights_2)):
#     print("{", end="")
#     for j in range (len(weights_2[0])-1):
#         print(f"{weights_2[i][j]},", end="")
#     print(f"{weights_2[i][63]}", end="")
#     print("},")

# for i in range (len(weights_3)):
#     print("{", end="")
#     for j in range (len(weights_3[0])-1):
#         print(f"{weights_3[i][j]},", end="")
#     print(f"{weights_3[i][len(weights_3[0])-1]}", end="")
#     print("},")    

print(len(weights_1))

{0.07100900262594223,0.04677070304751396,0.05774557590484619,-0.05035075917840004,0.1076270192861557,0.04734715446829796,-0.11223050206899643,0.06916490197181702,0.029008768498897552,-0.03996836021542549,0.11182451248168945,0.09823445230722427,-0.03720312938094139,-0.10866943746805191,0.12436194717884064,-0.03919755294919014,0.1484239101409912,-0.07729081064462662,0.08238670974969864,-0.11424844712018967,0.11907140165567398,-0.0766746774315834,-0.10720892250537872,-0.07419595122337341,-0.0764819011092186,0.07255466282367706,-0.056798141449689865,0.005001917015761137,0.00829352904111147,-0.020530641078948975,-0.08784864097833633,0.005323830060660839,-0.08633574843406677,-0.07418642938137054,-0.04431421309709549,0.06474603712558746,0.1491173654794693,0.043207619339227676,-0.10688890516757965,-0.048818714916706085,0.03354726359248161,-0.06856890767812729,-0.1084529459476471,0.1158207505941391,-0.10470716655254364,0.09482471644878387,-0.06384162604808807,0.11853254586458206,-0.017516598105

{0.036054350435733795,0.08590873330831528,-0.12065012007951736,0.018952250480651855,-0.002904573455452919,0.03542279079556465,-0.08232583105564117,0.050668682903051376,0.08904096484184265,-0.04991155490279198,0.0455697737634182,-0.1126137375831604,-0.09226644784212112,-0.07023163139820099,-0.014012587256729603,0.03907369449734688,-0.09161218255758286,0.09759373962879181,0.054744165390729904,-0.07989401370286942,-0.049435071647167206,-0.06466654688119888,-0.05475534498691559,-0.07604753971099854,0.019471358507871628,-0.004967461805790663,0.02481948211789131,0.03852929547429085,-0.01918243244290352,-0.06583134084939957,0.07585126906633377,-0.11407256871461868,0.0995391234755516,0.014253539964556694,-0.10840193927288055,0.04982588440179825,-0.010631297715008259,-0.10256509482860565,-0.04407667741179466,0.06251751631498337,0.02118978463113308,-0.047580964863300323,0.06474018096923828,0.06793628633022308,-0.09159716963768005,-0.0246141217648983,-0.06773830205202103,-0.10282492637634277,0.08

{-0.12387526035308838,0.017299875617027283,-0.09212770313024521,0.07396423816680908,0.041179392486810684,-0.09476390480995178,0.07618448883295059,0.08242727816104889,-0.03497975692152977,-0.020833592861890793,-0.12867428362369537,-0.02055884711444378,-0.0892951637506485,-0.03597690910100937,0.07236173003911972,-0.023417841643095016,0.06438078731298447,0.03236350044608116,0.07492467015981674,-0.07029574364423752,-0.10381252318620682,-0.006622187793254852,-0.03128812462091446,-0.1076449379324913,-0.014726693741977215,0.10595972836017609,0.04366384446620941,0.03901774808764458,-0.03323755040764809,-0.06590719521045685,0.10775984078645706,0.11800549179315567,-0.026523292064666748,-0.08687679469585419,-0.0009079772862605751,-0.05352802947163582,-0.1192762479186058,0.128181591629982,-0.05862950161099434,0.0051298015750944614,-0.022712115198373795,-0.056950122117996216,-0.04546503722667694,-0.048776913434267044,0.044315896928310394,-0.058481257408857346,0.053586192429065704,0.1183517947793006

{-0.12170567363500595,-0.03511707857251167,-0.035715650767087936,-0.08573798835277557,0.07189816236495972,0.038360826671123505,-0.10319973528385162,0.1208505630493164,-0.05133384093642235,-0.05039319396018982,0.13505128026008606,0.03102634847164154,-0.10921286046504974,0.11098004877567291,0.04748895391821861,-0.019324034452438354,0.0880781039595604,-0.0796363353729248,-0.05831865593791008,-0.10015369951725006,0.11372817307710648,-0.01767556183040142,-0.08790241181850433,0.030408870428800583,-0.10839860141277313,0.015655849128961563,0.01990276761353016,-0.08192446082830429,-0.05243721976876259,-0.03202062100172043,0.09796889871358871,-0.13319018483161926,-0.0900595411658287,0.02883223630487919,0.044752463698387146,-0.10142064094543457,0.09900999069213867,0.07989224046468735,-0.1260608434677124,-0.0827873945236206,0.07877850532531738,0.11427457630634308,-0.08974500000476837,-0.07339223474264145,-0.05901255086064339,0.04137781634926796,-0.04554492607712746,0.10894609987735748,-0.120903752

In [64]:
print(len(weights_3))
print(len(weights_3[0]))


for i in range (len(biases_2)-1):
        print(f"{biases_2[i]},", end="")
print(f"{biases_2[63]}")

print(biases_3)
for i in range (len(biases_3)-1):
        print(f"{biases_3[i]},", end="")
print(f"{biases_3[len(biases_3)-1]}", end="")


64
5
-0.017938604578375816,-0.01257814560085535,-0.015433087944984436,0.005697424057871103,0.0021321410313248634,0.003053578082472086,-0.00141071283724159,0.02228662185370922,-0.0011136176763102412,-0.003416439052671194,-0.0025086132809519768,0.005296347662806511,-0.005127785727381706,-0.0018455148674547672,-0.002784227952361107,-0.0027519247960299253,0.0002262843045173213,0.0011294763535261154,0.022957444190979004,0.00845971517264843,-0.008082367479801178,-0.010986458510160446,-0.0005964118172414601,0.002661960432305932,-0.019222373142838478,0.008302044123411179,-0.012101518921554089,0.014038946479558945,2.5911826924129855e-06,-0.02268196828663349,0.0209483839571476,-0.023190811276435852,-0.01099991612136364,-0.01618959940969944,0.004590191412717104,-0.006509758532047272,-0.011635392904281616,-0.002832920290529728,-0.013987310230731964,-0.013462339527904987,0.008927329443395138,-0.0077174208126962185,-0.0036659259349107742,-0.015089131891727448,0.0045163268223404884,-0.007694668136537

In [145]:

test_num = 19
for i in range(50):
    test_sam = scaled_samples[i]
    test_label = lable_list[i]

    q = model.predict(np.array([test_sam]))
    print(q)
    print(test_label)


    print(np.int8(q))

[[0. 0. 0. 0. 1.]]
4
[[0 0 0 0 1]]
[[4.7741786e-13 3.3839545e-20 4.5501620e-16 1.0000000e+00 1.1015055e-11]]
3
[[0 0 0 1 0]]
[[3.5222664e-17 5.5230369e-21 4.1463285e-13 1.0000000e+00 3.7232751e-19]]
3
[[0 0 0 1 0]]
[[0. 0. 0. 0. 1.]]
4
[[0 0 0 0 1]]
[[1.2741048e-13 2.0275039e-24 1.0000000e+00 6.4964109e-23 3.1973262e-16]]
2
[[0 0 1 0 0]]
[[8.0731678e-24 1.0000000e+00 2.4832219e-31 5.1414139e-17 1.5826319e-34]]
1
[[0 1 0 0 0]]
[[1.5556527e-10 4.3812087e-09 2.1066844e-11 1.0000000e+00 1.1633338e-17]]
3
[[0 0 0 1 0]]
[[1.0000000e+00 1.5156089e-30 1.1116811e-22 1.8882795e-37 1.2832374e-22]]
0
[[1 0 0 0 0]]
[[1.0000000e+00 3.4954941e-33 6.8191825e-21 3.4976168e-17 4.3479510e-28]]
0
[[1 0 0 0 0]]
[[2.6281037e-23 1.0000000e+00 4.1872362e-38 8.9145290e-24 1.2302250e-34]]
1
[[0 1 0 0 0]]
[[3.9238949e-22 2.0054172e-34 1.0000000e+00 1.3043431e-26 5.9640744e-25]]
2
[[0 0 1 0 0]]
[[5.9860773e-30 1.0000000e+00 5.0988962e-31 2.1648153e-15 4.2813796e-26]]
1
[[0 1 0 0 0]]
[[7.8595170e-31 4.4355303e-37 

In [56]:
print(len(test_sam))

print(max(0,-21))

300
0


In [82]:
%history -g -f log.txt


File 'log.txt' exists. Overwrite? y
Overwriting file.


In [73]:
lut_table = [0.000045,0.000046,0.000046,0.000047,0.000047,0.000048,0.000048,0.000049,0.000049,0.000050,0.000050,0.000051,0.000051,0.000052,0.000052,0.000053,0.000053,0.000054,0.000054,0.000055,0.000055,0.000056,0.000057,0.000057,0.000058,0.000058,0.000059,0.000059,0.000060,0.000061,0.000061,0.000062,0.000063,0.000063,0.000064,0.000064,0.000065,0.000066,0.000066,0.000067,0.000068,0.000068,0.000069,0.000070,0.000070,0.000071,0.000072,0.000073,0.000073,0.000074,0.000075,0.000076,0.000076,0.000077,0.000078,0.000079,0.000079,0.000080,0.000081,0.000082,0.000083,0.000084,0.000084,0.000085,0.000086,0.000087,0.000088,0.000089,0.000090,0.000091,0.000091,0.000092,0.000093,0.000094,0.000095,0.000096,0.000097,0.000098,0.000099,0.000100,0.000101,0.000102,0.000103,0.000104,0.000105,0.000106,0.000107,0.000108,0.000109,0.000111,0.000112,0.000113,0.000114,0.000115,0.000116,0.000117,0.000119,0.000120,0.000121,0.000122,0.000123,0.000125,0.000126,0.000127,0.000128,0.000130,0.000131,0.000132,0.000134,0.000135,0.000136,0.000138,0.000139,0.000141,0.000142,0.000143,0.000145,0.000146,0.000148,0.000149,0.000151,0.000152,0.000154,0.000155,0.000157,0.000158,0.000160,0.000162,0.000163,0.000165,0.000167,0.000168,0.000170,0.000172,0.000173,0.000175,0.000177,0.000179,0.000180,0.000182,0.000184,0.000186,0.000188,0.000190,0.000192,0.000194,0.000195,0.000197,0.000199,0.000201,0.000203,0.000206,0.000208,0.000210,0.000212,0.000214,0.000216,0.000218,0.000220,0.000223,0.000225,0.000227,0.000229,0.000232,0.000234,0.000236,0.000239,0.000241,0.000244,0.000246,0.000249,0.000251,0.000254,0.000256,0.000259,0.000261,0.000264,0.000267,0.000269,0.000272,0.000275,0.000277,0.000280,0.000283,0.000286,0.000289,0.000292,0.000295,0.000298,0.000301,0.000304,0.000307,0.000310,0.000313,0.000316,0.000319,0.000322,0.000326,0.000329,0.000332,0.000335,0.000339,0.000342,0.000346,0.000349,0.000353,0.000356,0.000360,0.000363,0.000367,0.000371,0.000374,0.000378,0.000382,0.000386,0.000390,0.000394,0.000398,0.000402,0.000406,0.000410,0.000414,0.000418,0.000422,0.000426,0.000431,0.000435,0.000439,0.000444,0.000448,0.000453,0.000457,0.000462,0.000467,0.000471,0.000476,0.000481,0.000486,0.000491,0.000495,0.000500,0.000505,0.000511,0.000516,0.000521,0.000526,0.000531,0.000537,0.000542,0.000548,0.000553,0.000559,0.000564,0.000570,0.000576,0.000581,0.000587,0.000593,0.000599,0.000605,0.000611,0.000617,0.000624,0.000630,0.000636,0.000643,0.000649,0.000656,0.000662,0.000669,0.000676,0.000682,0.000689,0.000696,0.000703,0.000710,0.000717,0.000725,0.000732,0.000739,0.000747,0.000754,0.000762,0.000769,0.000777,0.000785,0.000793,0.000801,0.000809,0.000817,0.000825,0.000833,0.000842,0.000850,0.000859,0.000867,0.000876,0.000885,0.000894,0.000903,0.000912,0.000921,0.000930,0.000940,0.000949,0.000959,0.000968,0.000978,0.000988,0.000998,0.001008,0.001018,0.001028,0.001038,0.001049,0.001059,0.001070,0.001081,0.001092,0.001103,0.001114,0.001125,0.001136,0.001148,0.001159,0.001171,0.001183,0.001195,0.001207,0.001219,0.001231,0.001243,0.001256,0.001268,0.001281,0.001294,0.001307,0.001320,0.001333,0.001347,0.001360,0.001374,0.001388,0.001402,0.001416,0.001430,0.001444,0.001459,0.001474,0.001488,0.001503,0.001519,0.001534,0.001549,0.001565,0.001581,0.001596,0.001612,0.001629,0.001645,0.001662,0.001678,0.001695,0.001712,0.001729,0.001747,0.001764,0.001782,0.001800,0.001818,0.001836,0.001855,0.001873,0.001892,0.001911,0.001930,0.001950,0.001969,0.001989,0.002009,0.002029,0.002050,0.002070,0.002091,0.002112,0.002133,0.002155,0.002177,0.002198,0.002221,0.002243,0.002265,0.002288,0.002311,0.002334,0.002358,0.002382,0.002405,0.002430,0.002454,0.002479,0.002504,0.002529,0.002554,0.002580,0.002606,0.002632,0.002658,0.002685,0.002712,0.002739,0.002767,0.002795,0.002823,0.002851,0.002880,0.002909,0.002938,0.002968,0.002997,0.003028,0.003058,0.003089,0.003120,0.003151,0.003183,0.003215,0.003247,0.003280,0.003313,0.003346,0.003380,0.003414,0.003448,0.003483,0.003518,0.003553,0.003589,0.003625,0.003661,0.003698,0.003735,0.003773,0.003810,0.003849,0.003887,0.003927,0.003966,0.004006,0.004046,0.004087,0.004128,0.004169,0.004211,0.004254,0.004296,0.004339,0.004383,0.004427,0.004472,0.004517,0.004562,0.004608,0.004654,0.004701,0.004748,0.004796,0.004844,0.004893,0.004942,0.004992,0.005042,0.005092,0.005144,0.005195,0.005248,0.005300,0.005354,0.005407,0.005462,0.005517,0.005572,0.005628,0.005685,0.005742,0.005799,0.005858,0.005917,0.005976,0.006036,0.006097,0.006158,0.006220,0.006282,0.006346,0.006409,0.006474,0.006539,0.006605,0.006671,0.006738,0.006806,0.006874,0.006943,0.007013,0.007083,0.007155,0.007227,0.007299,0.007372,0.007447,0.007521,0.007597,0.007673,0.007750,0.007828,0.007907,0.007987,0.008067,0.008148,0.008230,0.008312,0.008396,0.008480,0.008566,0.008652,0.008739,0.008826,0.008915,0.009005,0.009095,0.009187,0.009279,0.009372,0.009466,0.009562,0.009658,0.009755,0.009853,0.009952,0.010052,0.010153,0.010255,0.010358,0.010462,0.010567,0.010673,0.010781,0.010889,0.010998,0.011109,0.011221,0.011333,0.011447,0.011562,0.011679,0.011796,0.011914,0.012034,0.012155,0.012277,0.012401,0.012525,0.012651,0.012778,0.012907,0.013037,0.013168,0.013300,0.013434,0.013569,0.013705,0.013843,0.013982,0.014122,0.014264,0.014408,0.014552,0.014699,0.014846,0.014996,0.015146,0.015299,0.015452,0.015608,0.015764,0.015923,0.016083,0.016245,0.016408,0.016573,0.016739,0.016907,0.017077,0.017249,0.017422,0.017597,0.017774,0.017953,0.018133,0.018316,0.018500,0.018686,0.018873,0.019063,0.019255,0.019448,0.019644,0.019841,0.020041,0.020242,0.020445,0.020651,0.020858,0.021068,0.021280,0.021494,0.021710,0.021928,0.022148,0.022371,0.022596,0.022823,0.023052,0.023284,0.023518,0.023754,0.023993,0.024234,0.024478,0.024724,0.024972,0.025223,0.025476,0.025733,0.025991,0.026252,0.026516,0.026783,0.027052,0.027324,0.027598,0.027876,0.028156,0.028439,0.028725,0.029013,0.029305,0.029599,0.029897,0.030197,0.030501,0.030807,0.031117,0.031430,0.031746,0.032065,0.032387,0.032712,0.033041,0.033373,0.033709,0.034047,0.034390,0.034735,0.035084,0.035437,0.035793,0.036153,0.036516,0.036883,0.037254,0.037628,0.038006,0.038388,0.038774,0.039164,0.039557,0.039955,0.040357,0.040762,0.041172,0.041586,0.042004,0.042426,0.042852,0.043283,0.043718,0.044157,0.044601,0.045049,0.045502,0.045959,0.046421,0.046888,0.047359,0.047835,0.048316,0.048801,0.049292,0.049787,0.050287,0.050793,0.051303,0.051819,0.052340,0.052866,0.053397,0.053934,0.054476,0.055023,0.055576,0.056135,0.056699,0.057269,0.057844,0.058426,0.059013,0.059606,0.060205,0.060810,0.061421,0.062039,0.062662,0.063292,0.063928,0.064570,0.065219,0.065875,0.066537,0.067206,0.067881,0.068563,0.069252,0.069948,0.070651,0.071361,0.072078,0.072803,0.073535,0.074274,0.075020,0.075774,0.076536,0.077305,0.078082,0.078866,0.079659,0.080460,0.081268,0.082085,0.082910,0.083743,0.084585,0.085435,0.086294,0.087161,0.088037,0.088922,0.089815,0.090718,0.091630,0.092551,0.093481,0.094420,0.095369,0.096328,0.097296,0.098274,0.099261,0.100259,0.101266,0.102284,0.103312,0.104350,0.105399,0.106459,0.107528,0.108609,0.109701,0.110803,0.111917,0.113042,0.114178,0.115325,0.116484,0.117655,0.118837,0.120032,0.121238,0.122456,0.123687,0.124930,0.126186,0.127454,0.128735,0.130029,0.131336,0.132655,0.133989,0.135335,0.136695,0.138069,0.139457,0.140858,0.142274,0.143704,0.145148,0.146607,0.148080,0.149569,0.151072,0.152590,0.154124,0.155673,0.157237,0.158817,0.160414,0.162026,0.163654,0.165299,0.166960,0.168638,0.170333,0.172045,0.173774,0.175520,0.177284,0.179066,0.180866,0.182684,0.184520,0.186374,0.188247,0.190139,0.192050,0.193980,0.195930,0.197899,0.199888,0.201897,0.203926,0.205975,0.208045,0.210136,0.212248,0.214381,0.216536,0.218712,0.220910,0.223130,0.225373,0.227638,0.229925,0.232236,0.234570,0.236928,0.239309,0.241714,0.244143,0.246597,0.249075,0.251579,0.254107,0.256661,0.259240,0.261846,0.264477,0.267135,0.269820,0.272532,0.275271,0.278037,0.280832,0.283654,0.286505,0.289384,0.292293,0.295230,0.298197,0.301194,0.304221,0.307279,0.310367,0.313486,0.316637,0.319819,0.323033,0.326280,0.329559,0.332871,0.336216,0.339596,0.343009,0.346456,0.349938,0.353455,0.357007,0.360595,0.364219,0.367879,0.371577,0.375311,0.379083,0.382893,0.386741,0.390628,0.394554,0.398519,0.402524,0.406570,0.410656,0.414783,0.418952,0.423162,0.427415,0.431711,0.436049,0.440432,0.444858,0.449329,0.453845,0.458406,0.463013,0.467666,0.472367,0.477114,0.481909,0.486752,0.491644,0.496585,0.501576,0.506617,0.511709,0.516851,0.522046,0.527292,0.532592,0.537944,0.543351,0.548812,0.554327,0.559898,0.565525,0.571209,0.576950,0.582748,0.588605,0.594521,0.600496,0.606531,0.612626,0.618783,0.625002,0.631284,0.637628,0.644036,0.650509,0.657047,0.663650,0.670320,0.677057,0.683861,0.690734,0.697676,0.704688,0.711770,0.718924,0.726149,0.733447,0.740818,0.748264,0.755784,0.763379,0.771052,0.778801,0.786628,0.794534,0.802519,0.810584,0.818731,0.826959,0.835270,0.843665,0.852144,0.860708,0.869358,0.878095,0.886920,0.895834,0.904837,0.913931,0.923116,0.932394,0.941765,0.951229,0.960789,0.970446,0.980199,0.990050,1.000000,1.010050,1.020201,1.030455,1.040811,1.051271,1.061837,1.072508,1.083287,1.094174,1.105171,1.116278,1.127497,1.138828,1.150274,1.161834,1.173511,1.185305,1.197217,1.209250,1.221403,1.233678,1.246077,1.258600,1.271249,1.284025,1.296930,1.309964,1.323130,1.336427,1.349859,1.363425,1.377128,1.390968,1.404948,1.419068,1.433329,1.447735,1.462285,1.476981,1.491825,1.506818,1.521962,1.537258,1.552707,1.568312,1.584074,1.599994,1.616074,1.632316,1.648721,1.665291,1.682028,1.698932,1.716007,1.733253,1.750673,1.768267,1.786038,1.803988,1.822119,1.840431,1.858928,1.877611,1.896481,1.915541,1.934792,1.954237,1.973878,1.993716,2.013753,2.033991,2.054433,2.075081,2.095936,2.117000,2.138276,2.159766,2.181472,2.203396,2.225541,2.247908,2.270500,2.293319,2.316367,2.339647,2.363161,2.386911,2.410900,2.435130,2.459603,2.484323,2.509290,2.534509,2.559981,2.585710,2.611696,2.637944,2.664456,2.691234,2.718282,2.745601,2.773195,2.801066,2.829217,2.857651,2.886371,2.915379,2.944680,2.974274,3.004166,3.034358,3.064854,3.095657,3.126768,3.158193,3.189933,3.221993,3.254374,3.287081,3.320117,3.353485,3.387188,3.421230,3.455613,3.490343,3.525421,3.560853,3.596640,3.632787,3.669297,3.706174,3.743421,3.781043,3.819044,3.857426,3.896193,3.935351,3.974902,4.014850,4.055200,4.095955,4.137120,4.178699,4.220696,4.263115,4.305960,4.349235,4.392946,4.437096,4.481689,4.526731,4.572225,4.618177,4.664590,4.711470,4.758821,4.806648,4.854956,4.903749,4.953032,5.002811,5.053090,5.103875,5.155170,5.206980,5.259311,5.312168,5.365556,5.419481,5.473947,5.528961,5.584528,5.640654,5.697343,5.754603,5.812437,5.870853,5.929856,5.989452,6.049647,6.110447,6.171858,6.233887,6.296538,6.359820,6.423737,6.488296,6.553505,6.619369,6.685894,6.753089,6.820958,6.889510,6.958751,7.028688,7.099327,7.170676,7.242743,7.315534,7.389056,7.463317,7.538325,7.614086,7.690609,7.767901,7.845970,7.924823,8.004469,8.084915,8.166170,8.248241,8.331137,8.414867,8.499438,8.584858,8.671138,8.758284,8.846306,8.935213,9.025013,9.115716,9.207331,9.299866,9.393331,9.487736,9.583089,9.679401,9.776680,9.874938,9.974182,10.074425,10.175674,10.277942,10.381237,10.485570,10.590951,10.697392,10.804903,10.913494,11.023176,11.133961,11.245859,11.358882,11.473041,11.588347,11.704812,11.822447,11.941264,12.061276,12.182494,12.304930,12.428597,12.553506,12.679671,12.807104,12.935817,13.065824,13.197138,13.329772,13.463738,13.599051,13.735724,13.873770,14.013204,14.154039,14.296289,14.439969,14.585093,14.731676,14.879732,15.029276,15.180322,15.332887,15.486985,15.642632,15.799843,15.958634,16.119021,16.281020,16.444647,16.609918,16.776851,16.945461,17.115766,17.287782,17.461527,17.637018,17.814273,17.993310,18.174145,18.356799,18.541287,18.727630,18.915846,19.105954,19.297972,19.491920,19.687817,19.885682,20.085537,20.287400,20.491292,20.697233,20.905243,21.115344,21.327557,21.541903,21.758402,21.977078,22.197951,22.421044,22.646380,22.873980,23.103867,23.336065,23.570596,23.807484,24.046754,24.288427,24.532530,24.779086,25.028120,25.279657,25.533722,25.790340,26.049537,26.311339,26.575773,26.842864,27.112639,27.385125,27.660351,27.938342,28.219127,28.502734,28.789191,29.078527,29.370771,29.665952,29.964100,30.265244,30.569415,30.876643,31.186958,31.500392,31.816977,32.136742,32.459722,32.785948,33.115452,33.448268,33.784428,34.123968,34.466919,34.813317,35.163197,35.516593,35.873541,36.234076,36.598234,36.966053,37.337568,37.712817,38.091837,38.474666,38.861343,39.251906,39.646394,40.044847,40.447304,40.853807,41.264394,41.679108,42.097990,42.521082,42.948426,43.380065,43.816042,44.256400,44.701184,45.150439,45.604208,46.062538,46.525474,46.993063,47.465351,47.942386,48.424215,48.910887,49.402449,49.898952,50.400445,50.906978,51.418601,51.935367,52.457326,52.984531,53.517034,54.054889,54.598150,55.146871,55.701106,56.260911,56.826343,57.397457,57.974311,58.556963,59.145470,59.739892,60.340288,60.946718,61.559242,62.177923,62.802821,63.434000,64.071523,64.715452,65.365853,66.022791,66.686331,67.356540,68.033484,68.717232,69.407852,70.105412,70.809983,71.521636,72.240440,72.966468,73.699794,74.440489,75.188628,75.944287,76.707539,77.478463,78.257134,79.043632,79.838033,80.640419,81.450869,82.269464,83.096285,83.931417,84.774942,85.626944,86.487509,87.356723,88.234673,89.121446,90.017131,90.921819,91.835598,92.758561,93.690800,94.632408,95.583480,96.544110,97.514394,98.494430,99.484316,100.484150,101.494032,102.514064,103.544348,104.584986,105.636082,106.697742,107.770073,108.853180,109.947172,111.052160,112.168253,113.295562,114.434202,115.584285,116.745926,117.919242,119.104350,120.301369,121.510418,122.731618,123.965091,125.210961,126.469352,127.740390,129.024202,130.320917,131.630664,132.953574,134.289780,135.639414,137.002613,138.379512,139.770250,141.174964,142.593796,144.026887,145.474382,146.936423,148.413159,149.904736,151.411304,152.933013,154.470015,156.022464,157.590516,159.174327,160.774056,162.389862,164.021907,165.670355,167.335370,169.017118,170.715768,172.431490,174.164456,175.914837,177.682811,179.468553,181.272242,183.094058,184.934184,186.792804,188.670102,190.566268,192.481491,194.415962,196.369875,198.343425,200.336810,202.350228,204.383882,206.437974,208.512710,210.608298,212.724946,214.862868,217.022275,219.203386,221.406416,223.631588,225.879123,228.149245,230.442183,232.758166,235.097424,237.460193,239.846707,242.257207,244.691932,247.151127,249.635037,252.143911,254.677999,257.237556,259.822836,262.434099,265.071606,267.735620,270.426407,273.144238,275.889383,278.662118,281.462718,284.291466,287.148643,290.034534,292.949430,295.893621,298.867401,301.871068,304.904923,307.969268,311.064411,314.190660,317.348329,320.537733,323.759190,327.013024,330.299560,333.619126,336.972054,340.358679,343.779341,347.234380,350.724144,354.248980,357.809242,361.405284,365.037468,368.706155,372.411714,376.154514,379.934930,383.753339,387.610124,391.505671,395.440368,399.414610,403.428793,407.483320,411.578596,415.715029,419.893035,424.113030,428.375437,432.680682,437.029195,441.421411,445.857770,450.338715,454.864694,459.436161,464.053571,468.717387,473.428075,478.186106,482.991956,487.846106,492.749041,497.701251,502.703232,507.755483,512.858511,518.012825,523.218940,528.477378,533.788664,539.153329,544.571910,550.044949,555.572992,561.156594,566.796311,572.492709,578.246356,584.057829,589.927708,595.856580,601.845038,607.893681,614.003114,620.173948,626.406800,632.702293,639.061057,645.483727,651.970946,658.523363,665.141633,671.826418,678.578385,685.398211,692.286578,699.244174,706.271695,713.369843,720.539329,727.780870,735.095189,742.483019,749.945097,757.482171,765.094993,772.784326,780.550937,788.395604,796.319112,804.322252,812.405825,820.570639,828.817511,837.147266,845.560736,854.058763,862.642196,871.311894,880.068724,888.913562,897.847292,906.870807,915.985010,925.190812,934.489135,943.880907,953.367067,962.948566,972.626360,982.401417,992.274716,1002.247242,1012.319995,1022.493980,1032.770215,1043.149728,1053.633557,1064.222751,1074.918367,1085.721476,1096.633158,1107.654505,1118.786618,1130.030610,1141.387607,1152.858743,1164.445166,1176.148034,1187.968519,1199.907801,1211.967074,1224.147546,1236.450433,1248.876967,1261.428389,1274.105955,1286.910933,1299.844603,1312.908258,1326.103206,1339.430764,1352.892267,1366.489061,1380.222504,1394.093971,1408.104848,1422.256537,1436.550453,1450.988025,1465.570697,1480.299928,1495.177189,1510.203970,1525.381772,1540.712114,1556.196528,1571.836563,1587.633783,1603.589768,1619.706113,1635.984430,1652.426347,1669.033508,1685.807573,1702.750221,1719.863145,1737.148057,1754.606686,1772.240776,1790.052092,1808.042414,1826.213543,1844.567294,1863.105504,1881.830025,1900.742731,1919.845513,1939.140282,1958.628965,1978.313514,1998.195895,2018.278098,2038.562130,2059.050020,2079.743817,2100.645589,2121.757429,2143.081445,2164.619772,2186.374562,2208.347992,2230.542258,2252.959581,2275.602201,2298.472383,2321.572415,2344.904605,2368.471288,2392.274821,2416.317582,2440.601978,2465.130435,2489.905408,2514.929373,2540.204834,2565.734317,2591.520375,2617.565588,2643.872560,2670.443921,2697.282328,2724.390466,2751.771046,2779.426805,2807.360508,2835.574950,2864.072953,2892.857364,2921.931064,2951.296959,2980.957987,3010.917113,3041.177333,3071.741673,3102.613190,3133.794971,3165.290134,3197.101829,3229.233237,3261.687570,3294.468075,3327.578030,3361.020745,3394.799565,3428.917868,3463.379065,3498.186604,3533.343964,3568.854661,3604.722246,3640.950307,3677.542466,3714.502383,3751.833752,3789.540308,3827.625821,3866.094100,3904.948992,3944.194382,3983.834195,4023.872394,4064.312984,4105.160008,4146.417552,4188.089741,4230.180743,4272.694766,4315.636063,4359.008926,4402.817694,4447.066748,4491.760512,4536.903455,4582.500093,4628.554985,4675.072736,4722.057998,4769.515469,4817.449897,4865.866073,4914.768840,4964.163088,5014.053757,5064.445835,5115.344362,5166.754427,5218.681172,5271.129790,5324.105525,5377.613675,5431.659591,5486.248678,5541.386394,5597.078253,5653.329824,5710.146734,5767.534663,5825.499350,5884.046591,5943.182243,6002.912217,6063.242488,6124.179088,6185.728111,6247.895712,6310.688108,6374.111578,6438.172464,6502.877173,6568.232175,6634.244006,6700.919267,6768.264625,6836.286816,6904.992640,6974.388970,7044.482745,7115.280973,7186.790736,7259.019183,7331.973539,7405.661098,7480.089230,7555.265376,7631.197056,7707.891861,7785.357462,7863.601605,7942.632116,8022.456895,8103.083928,8184.521275,8266.777081,8349.859572,8433.777056,8518.537925,8604.150654,8690.623806,8777.966027,8866.186052,8955.292703,9045.294891,9136.201616,9228.021969,9320.765132,9414.440379,9509.057078,9604.624690,9701.152773,9798.650979,9897.129059,9996.596859,10097.064328,10198.541512,10301.038558,10404.565717,10509.133340,10614.751886,10721.431916,10829.184099,10938.019208,11047.948129,11158.981853,11271.131486,11384.408240,11498.823445,11614.388542,11731.115087,11849.014754,11968.099332,12088.380730,12209.870976,12332.582220,12456.526732,12581.716907,12708.165264,12835.884448,12964.887231,13095.186514,13226.795327,13359.726830,13493.994316,13629.611214,13766.591084,13904.947625,14044.694672,14185.846200,14328.416324,14472.419302,14617.869534,14764.781566,14913.170087,15063.049938,15214.436107,15367.343732,15521.788104,15677.784668,15835.349024,15994.496927,16155.244294,16317.607198,16481.601877,16647.244729,16814.552320,16983.541381,17154.228809,17326.631675,17500.767218,17676.652853,17854.306168,18033.744928,18214.987078,18398.050741,18582.954225,18769.716020,18958.354802,19148.889435,19341.338974,19535.722662,19732.059939,19930.370438,20130.673991,20332.990628,20537.340581,20743.744286,20952.222382,21162.795718,21375.485350,21590.312550,21807.298798]
print(len(lut_table))

print(lut_table[1010])

2000
1.105171


In [96]:
weights_1 = model.layers[1].get_weights()[0]
biases_1 = model.layers[1].get_weights()[1]


weights_2 = model.layers[2].get_weights()[0]
biases_2  = model.layers[2].get_weights()[1]

weights_3 = model.layers[3].get_weights()[0]
biases_3  = model.layers[3].get_weights()[1]


max_int = 0
min_int = 0

for k in range(20):
    
    
    test_sam = scaled_samples[1260+k]
    test_label = lable_list[1260+k]
    q = model.predict(np.array([test_sam]))

    
    results = []
    results_2 = []
    results_3 = []


    number_nodes = 64
    number_inputs = 300
    output_nodes = 5
#     print(len(weights_1))
#     print(len(weights_1[0]))

    sum = 0

    for i in range(number_nodes):
        for j in range(number_inputs):
            sum += test_sam[j] * weights_1[j][i]
        sum += biases_1[i]
        results.append(max(0, sum))
        sum = 0

    sum = 0

    for i in range(number_nodes):
        for j in range(len(results)):
            sum += results[j] * weights_2[j][i]
        sum += biases_2[i]
        results_2.append(max(0, sum))
        sum = 0

    sum = 0

    for i in range(output_nodes):
        for j in range(len(results)):
            sum += results_2[j] * weights_3[j][i]
        sum += biases_3[i]
        results_3.append(sum)
        sum = 0
    
    print(results_3)   
    print(np.int8(results_3))   
# #     if max(results) > max_int:
# #         max_int = max(results)
# #     if max(results_2) > max_int:
# #         max_int = max(results_2)
#     if max(results_3) > max_int:
#         max_int = max(results_3)
#         print(k)


# #     if min(results) < min_int:
# #         min_int = min(results)
# #     if min(results_2) < min_int:
# #         min_int = min(results_2)
#     if min(results_3) < min_int:
#         min_int = min(results_3)
#     if int(np.argmax(q)) != int(np.argmax(results_3)):
#         print(int(np.argmax(q)), int(np.argmax(results_3)))



# print(max_int,min_int)

[-25.92021639913754, -39.24430620085715, 21.530657431896888, 32.445402611411225, -54.03516149947404]
[-25 -39  21  32 -54]
[-12.985613302297299, -61.238292015426936, 89.20318934803436, 5.592357180312554, -18.142541487387874]
[-12 -61  89   5 -18]
[-50.863303935989094, -103.64354828864614, -82.59382795506671, -77.8635168840101, 50.11024205791117]
[ -50 -103  -82  -77   50]
[40.5776698042223, -41.94993721797583, -89.07797290159385, -86.2124342870644, -45.40379833049914]
[ 40 -41 -89 -86 -45]
[-66.09909588826913, 88.83111024854804, -26.45708441892568, -9.575040706275207, -29.63272006109089]
[-66  88 -26  -9 -29]
[-18.574744428400685, -34.627006821902704, -12.574960799839163, 64.48789605577699, -58.1259395952265]
[-18 -34 -12  64 -58]
[-30.53149662938477, -59.39096029261525, -7.827000611117722, 49.22769841620649, -57.94831959320315]
[-30 -59  -7  49 -57]
[-31.85836856192234, -28.41475376882646, -30.057695783862634, 18.63741488622978, -47.600442644613395]
[-31 -28 -30  18 -47]
[15.597639612

In [80]:
print(np.exp(190))

3.2805870153846705e+82
